// Antimetal API definitions
// Copyright Antimetal, Inc. All rights reserved.
//
// Use of this source code and APIs are governed by a source available license that can be found in
// the LICENSE file or at:
// https://polyformproject.org/wp-content/uploads/2020/06/PolyForm-Shield-1.0.0.txt

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: network/v1/network.proto

package networkv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Represents a relationship between two network resources where subject
// forwards traffic to object.
// Inverse of RoutedFrom.
type RoutesTo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoutesTo) Reset() {
	*x = RoutesTo{}
	mi := &file_network_v1_network_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoutesTo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoutesTo) ProtoMessage() {}

func (x *RoutesTo) ProtoReflect() protoreflect.Message {
	mi := &file_network_v1_network_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoutesTo.ProtoReflect.Descriptor instead.
func (*RoutesTo) Descriptor() ([]byte, []int) {
	return file_network_v1_network_proto_rawDescGZIP(), []int{0}
}

// Represents a relationship between two network resources where subject receives
// traffic from object.
// Inverse of RoutesTo.
type RoutedFrom struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoutedFrom) Reset() {
	*x = RoutedFrom{}
	mi := &file_network_v1_network_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoutedFrom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoutedFrom) ProtoMessage() {}

func (x *RoutedFrom) ProtoReflect() protoreflect.Message {
	mi := &file_network_v1_network_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoutedFrom.ProtoReflect.Descriptor instead.
func (*RoutedFrom) Descriptor() ([]byte, []int) {
	return file_network_v1_network_proto_rawDescGZIP(), []int{1}
}

var File_network_v1_network_proto protoreflect.FileDescriptor

const file_network_v1_network_proto_rawDesc = "" +
	"\n" +
	"\x18network/v1/network.proto\x12\n" +
	"network.v1\"\n" +
	"\n" +
	"\bRoutesTo\"\f\n" +
	"\n" +
	"RoutedFromB\xa0\x01\n" +
	"\x0ecom.network.v1B\fNetworkProtoP\x01Z7github.com/antimetal/agent/pkg/api/network/v1;networkv1\xa2\x02\x03NXX\xaa\x02\n" +
	"Network.V1\xca\x02\n" +
	"Network\\V1\xe2\x02\x16Network\\V1\\GPBMetadata\xea\x02\vNetwork::V1b\x06proto3"

var (
	file_network_v1_network_proto_rawDescOnce sync.Once
	file_network_v1_network_proto_rawDescData []byte
)

func file_network_v1_network_proto_rawDescGZIP() []byte {
	file_network_v1_network_proto_rawDescOnce.Do(func() {
		file_network_v1_network_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_network_v1_network_proto_rawDesc), len(file_network_v1_network_proto_rawDesc)))
	})
	return file_network_v1_network_proto_rawDescData
}

var file_network_v1_network_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_network_v1_network_proto_goTypes = []any{
	(*RoutesTo)(nil),   // 0: network.v1.RoutesTo
	(*RoutedFrom)(nil), // 1: network.v1.RoutedFrom
}
var file_network_v1_network_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_network_v1_network_proto_init() }
func file_network_v1_network_proto_init() {
	if File_network_v1_network_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_network_v1_network_proto_rawDesc), len(file_network_v1_network_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_network_v1_network_proto_goTypes,
		DependencyIndexes: file_network_v1_network_proto_depIdxs,
		MessageInfos:      file_network_v1_network_proto_msgTypes,
	}.Build()
	File_network_v1_network_proto = out.File
	file_network_v1_network_proto_goTypes = nil
	file_network_v1_network_proto_depIdxs = nil
}
