// Antimetal API definitions
// Copyright Antimetal, Inc. All rights reserved.
//
// Use of this source code and APIs are governed by a source available license that can be found in
// the LICENSE file or at:
// https://polyformproject.org/wp-content/uploads/2020/06/PolyForm-Shield-1.0.0.txt

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: resource/v1/namespace.proto

package resourcev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Namespace is a scope for a resource.
type Namespace struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Namespace:
	//
	//	*Namespace_Cloud
	//	*Namespace_Kube
	Namespace     isNamespace_Namespace `protobuf_oneof:"namespace"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Namespace) Reset() {
	*x = Namespace{}
	mi := &file_resource_v1_namespace_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Namespace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Namespace) ProtoMessage() {}

func (x *Namespace) ProtoReflect() protoreflect.Message {
	mi := &file_resource_v1_namespace_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Namespace.ProtoReflect.Descriptor instead.
func (*Namespace) Descriptor() ([]byte, []int) {
	return file_resource_v1_namespace_proto_rawDescGZIP(), []int{0}
}

func (x *Namespace) GetNamespace() isNamespace_Namespace {
	if x != nil {
		return x.Namespace
	}
	return nil
}

func (x *Namespace) GetCloud() *CloudNamespace {
	if x != nil {
		if x, ok := x.Namespace.(*Namespace_Cloud); ok {
			return x.Cloud
		}
	}
	return nil
}

func (x *Namespace) GetKube() *KubernetesNamespace {
	if x != nil {
		if x, ok := x.Namespace.(*Namespace_Kube); ok {
			return x.Kube
		}
	}
	return nil
}

type isNamespace_Namespace interface {
	isNamespace_Namespace()
}

type Namespace_Cloud struct {
	Cloud *CloudNamespace `protobuf:"bytes,1,opt,name=cloud,proto3,oneof"`
}

type Namespace_Kube struct {
	Kube *KubernetesNamespace `protobuf:"bytes,2,opt,name=kube,proto3,oneof"`
}

func (*Namespace_Cloud) isNamespace_Namespace() {}

func (*Namespace_Kube) isNamespace_Namespace() {}

// CloudNamespace specifies the namespace scope for cloud resources.
type CloudNamespace struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       *ProviderAccount       `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Region        string                 `protobuf:"bytes,2,opt,name=region,proto3" json:"region,omitempty"`
	Group         string                 `protobuf:"bytes,3,opt,name=group,proto3" json:"group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloudNamespace) Reset() {
	*x = CloudNamespace{}
	mi := &file_resource_v1_namespace_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloudNamespace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloudNamespace) ProtoMessage() {}

func (x *CloudNamespace) ProtoReflect() protoreflect.Message {
	mi := &file_resource_v1_namespace_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloudNamespace.ProtoReflect.Descriptor instead.
func (*CloudNamespace) Descriptor() ([]byte, []int) {
	return file_resource_v1_namespace_proto_rawDescGZIP(), []int{1}
}

func (x *CloudNamespace) GetAccount() *ProviderAccount {
	if x != nil {
		return x.Account
	}
	return nil
}

func (x *CloudNamespace) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *CloudNamespace) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

// KubernetesNamespace specifies the namespace scope for Kubernetes resources.
type KubernetesNamespace struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cluster       string                 `protobuf:"bytes,1,opt,name=cluster,proto3" json:"cluster,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KubernetesNamespace) Reset() {
	*x = KubernetesNamespace{}
	mi := &file_resource_v1_namespace_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KubernetesNamespace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KubernetesNamespace) ProtoMessage() {}

func (x *KubernetesNamespace) ProtoReflect() protoreflect.Message {
	mi := &file_resource_v1_namespace_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KubernetesNamespace.ProtoReflect.Descriptor instead.
func (*KubernetesNamespace) Descriptor() ([]byte, []int) {
	return file_resource_v1_namespace_proto_rawDescGZIP(), []int{2}
}

func (x *KubernetesNamespace) GetCluster() string {
	if x != nil {
		return x.Cluster
	}
	return ""
}

func (x *KubernetesNamespace) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

var File_resource_v1_namespace_proto protoreflect.FileDescriptor

const file_resource_v1_namespace_proto_rawDesc = "" +
	"\n" +
	"\x1bresource/v1/namespace.proto\x12\vresource.v1\x1a\x1aresource/v1/provider.proto\"\x85\x01\n" +
	"\tNamespace\x123\n" +
	"\x05cloud\x18\x01 \x01(\v2\x1b.resource.v1.CloudNamespaceH\x00R\x05cloud\x126\n" +
	"\x04kube\x18\x02 \x01(\v2 .resource.v1.KubernetesNamespaceH\x00R\x04kubeB\v\n" +
	"\tnamespace\"v\n" +
	"\x0eCloudNamespace\x126\n" +
	"\aaccount\x18\x01 \x01(\v2\x1c.resource.v1.ProviderAccountR\aaccount\x12\x16\n" +
	"\x06region\x18\x02 \x01(\tR\x06region\x12\x14\n" +
	"\x05group\x18\x03 \x01(\tR\x05group\"M\n" +
	"\x13KubernetesNamespace\x12\x18\n" +
	"\acluster\x18\x01 \x01(\tR\acluster\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespaceB\xa9\x01\n" +
	"\x0fcom.resource.v1B\x0eNamespaceProtoP\x01Z9github.com/antimetal/agent/pkg/api/resource/v1;resourcev1\xa2\x02\x03RXX\xaa\x02\vResource.V1\xca\x02\vResource\\V1\xe2\x02\x17Resource\\V1\\GPBMetadata\xea\x02\fResource::V1b\x06proto3"

var (
	file_resource_v1_namespace_proto_rawDescOnce sync.Once
	file_resource_v1_namespace_proto_rawDescData []byte
)

func file_resource_v1_namespace_proto_rawDescGZIP() []byte {
	file_resource_v1_namespace_proto_rawDescOnce.Do(func() {
		file_resource_v1_namespace_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_resource_v1_namespace_proto_rawDesc), len(file_resource_v1_namespace_proto_rawDesc)))
	})
	return file_resource_v1_namespace_proto_rawDescData
}

var file_resource_v1_namespace_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_resource_v1_namespace_proto_goTypes = []any{
	(*Namespace)(nil),           // 0: resource.v1.Namespace
	(*CloudNamespace)(nil),      // 1: resource.v1.CloudNamespace
	(*KubernetesNamespace)(nil), // 2: resource.v1.KubernetesNamespace
	(*ProviderAccount)(nil),     // 3: resource.v1.ProviderAccount
}
var file_resource_v1_namespace_proto_depIdxs = []int32{
	1, // 0: resource.v1.Namespace.cloud:type_name -> resource.v1.CloudNamespace
	2, // 1: resource.v1.Namespace.kube:type_name -> resource.v1.KubernetesNamespace
	3, // 2: resource.v1.CloudNamespace.account:type_name -> resource.v1.ProviderAccount
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_resource_v1_namespace_proto_init() }
func file_resource_v1_namespace_proto_init() {
	if File_resource_v1_namespace_proto != nil {
		return
	}
	file_resource_v1_provider_proto_init()
	file_resource_v1_namespace_proto_msgTypes[0].OneofWrappers = []any{
		(*Namespace_Cloud)(nil),
		(*Namespace_Kube)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_resource_v1_namespace_proto_rawDesc), len(file_resource_v1_namespace_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_resource_v1_namespace_proto_goTypes,
		DependencyIndexes: file_resource_v1_namespace_proto_depIdxs,
		MessageInfos:      file_resource_v1_namespace_proto_msgTypes,
	}.Build()
	File_resource_v1_namespace_proto = out.File
	file_resource_v1_namespace_proto_goTypes = nil
	file_resource_v1_namespace_proto_depIdxs = nil
}
