// Antimetal API definitions
// Copyright Antimetal, Inc. All rights reserved.
//
// Use of this source code and APIs are governed by a source available license that can be found in
// the LICENSE file or at:
// https://polyformproject.org/wp-content/uploads/2020/06/PolyForm-Shield-1.0.0.txt

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: resource/v1/object.proto

package resourcev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TypeDescriptor describes an object type.
type TypeDescriptor struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The object kind full url (e.g. resource.v1.Resource,
	// resource.v1.Relationship). Kind represetnts the graph entity type. It
	// denotes whether the object is a "Resource" (graph node) or a "Relationship"
	// (graph edge).
	Kind string `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	// The object type. This should be the full url of the protobuf type
	// of the object schema.
	Type          string `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TypeDescriptor) Reset() {
	*x = TypeDescriptor{}
	mi := &file_resource_v1_object_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TypeDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TypeDescriptor) ProtoMessage() {}

func (x *TypeDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_resource_v1_object_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TypeDescriptor.ProtoReflect.Descriptor instead.
func (*TypeDescriptor) Descriptor() ([]byte, []int) {
	return file_resource_v1_object_proto_rawDescGZIP(), []int{0}
}

func (x *TypeDescriptor) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *TypeDescriptor) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

// Object is a resource or relationship object.
type Object struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Describes the object type.
	Type *TypeDescriptor `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// The Resource or Relationship object
	Object *anypb.Any `protobuf:"bytes,2,opt,name=object,proto3" json:"object,omitempty"`
	// Time-to-live value for the object. For each object, a timer is started.
	// The timer is reset each time the object is received with a new TTL.
	// If the object is received with no TTL set, the timer is removed for the
	// object. Upon expiration of the timer, the object is considered deleted.
	//
	// The TTL can be refreshed or changed by sending a Delta containing an Object
	// with the same name that doesn't change the object version. In this case the
	// object field does not need to be populated, which allows for light-weight
	// "heartbeat" updates to keep an object with a TTL alive.
	//
	// The TTL feature is meant to support cleaning up objects in the event of
	// a systems-agent removal/failure. For example, if the Kubernetes cluster
	// where the systems agent is deployed in is spun down, then all the resources
	// from the cluster will be deleted from the graph once the TTL expires.
	Ttl *durationpb.Duration `protobuf:"bytes,3,opt,name=ttl,proto3" json:"ttl,omitempty"`
	// The delta version of the Delta change set that the object is a part of.
	// It is used to keep track of the state of individual objects. The version is
	// set and maintained by the client sending Deltas.
	//
	// NOTE: the version string should only be used for comparisions!
	// It is not guaranteed that the version string is monotonically increasing.
	DeltaVersion  string `protobuf:"bytes,4,opt,name=delta_version,json=deltaVersion,proto3" json:"delta_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Object) Reset() {
	*x = Object{}
	mi := &file_resource_v1_object_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Object) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Object) ProtoMessage() {}

func (x *Object) ProtoReflect() protoreflect.Message {
	mi := &file_resource_v1_object_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Object.ProtoReflect.Descriptor instead.
func (*Object) Descriptor() ([]byte, []int) {
	return file_resource_v1_object_proto_rawDescGZIP(), []int{1}
}

func (x *Object) GetType() *TypeDescriptor {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *Object) GetObject() *anypb.Any {
	if x != nil {
		return x.Object
	}
	return nil
}

func (x *Object) GetTtl() *durationpb.Duration {
	if x != nil {
		return x.Ttl
	}
	return nil
}

func (x *Object) GetDeltaVersion() string {
	if x != nil {
		return x.DeltaVersion
	}
	return ""
}

var File_resource_v1_object_proto protoreflect.FileDescriptor

const file_resource_v1_object_proto_rawDesc = "" +
	"\n" +
	"\x18resource/v1/object.proto\x12\vresource.v1\x1a\x19google/protobuf/any.proto\x1a\x1egoogle/protobuf/duration.proto\"8\n" +
	"\x0eTypeDescriptor\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\"\xb9\x01\n" +
	"\x06Object\x12/\n" +
	"\x04type\x18\x01 \x01(\v2\x1b.resource.v1.TypeDescriptorR\x04type\x12,\n" +
	"\x06object\x18\x02 \x01(\v2\x14.google.protobuf.AnyR\x06object\x12+\n" +
	"\x03ttl\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\x03ttl\x12#\n" +
	"\rdelta_version\x18\x04 \x01(\tR\fdeltaVersionB\xa6\x01\n" +
	"\x0fcom.resource.v1B\vObjectProtoP\x01Z9github.com/antimetal/agent/pkg/api/resource/v1;resourcev1\xa2\x02\x03RXX\xaa\x02\vResource.V1\xca\x02\vResource\\V1\xe2\x02\x17Resource\\V1\\GPBMetadata\xea\x02\fResource::V1b\x06proto3"

var (
	file_resource_v1_object_proto_rawDescOnce sync.Once
	file_resource_v1_object_proto_rawDescData []byte
)

func file_resource_v1_object_proto_rawDescGZIP() []byte {
	file_resource_v1_object_proto_rawDescOnce.Do(func() {
		file_resource_v1_object_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_resource_v1_object_proto_rawDesc), len(file_resource_v1_object_proto_rawDesc)))
	})
	return file_resource_v1_object_proto_rawDescData
}

var file_resource_v1_object_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_resource_v1_object_proto_goTypes = []any{
	(*TypeDescriptor)(nil),      // 0: resource.v1.TypeDescriptor
	(*Object)(nil),              // 1: resource.v1.Object
	(*anypb.Any)(nil),           // 2: google.protobuf.Any
	(*durationpb.Duration)(nil), // 3: google.protobuf.Duration
}
var file_resource_v1_object_proto_depIdxs = []int32{
	0, // 0: resource.v1.Object.type:type_name -> resource.v1.TypeDescriptor
	2, // 1: resource.v1.Object.object:type_name -> google.protobuf.Any
	3, // 2: resource.v1.Object.ttl:type_name -> google.protobuf.Duration
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_resource_v1_object_proto_init() }
func file_resource_v1_object_proto_init() {
	if File_resource_v1_object_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_resource_v1_object_proto_rawDesc), len(file_resource_v1_object_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_resource_v1_object_proto_goTypes,
		DependencyIndexes: file_resource_v1_object_proto_depIdxs,
		MessageInfos:      file_resource_v1_object_proto_msgTypes,
	}.Build()
	File_resource_v1_object_proto = out.File
	file_resource_v1_object_proto_goTypes = nil
	file_resource_v1_object_proto_depIdxs = nil
}
