// Antimetal API definitions
// Copyright Antimetal, Inc. All rights reserved.
//
// Use of this source code and APIs are governed by a source available license that can be found in
// the LICENSE file or at:
// https://polyformproject.org/wp-content/uploads/2020/06/PolyForm-Shield-1.0.0.txt

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: resource/v1/provider.proto

package resourcev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Provider is an entity that serves a resource
type Provider int32

const (
	Provider_PROVIDER_OTHER      Provider = 0
	Provider_PROVIDER_AWS        Provider = 1
	Provider_PROVIDER_GCP        Provider = 2
	Provider_PROVIDER_AZURE      Provider = 3
	Provider_PROVIDER_KUBERNETES Provider = 4
)

// Enum value maps for Provider.
var (
	Provider_name = map[int32]string{
		0: "PROVIDER_OTHER",
		1: "PROVIDER_AWS",
		2: "PROVIDER_GCP",
		3: "PROVIDER_AZURE",
		4: "PROVIDER_KUBERNETES",
	}
	Provider_value = map[string]int32{
		"PROVIDER_OTHER":      0,
		"PROVIDER_AWS":        1,
		"PROVIDER_GCP":        2,
		"PROVIDER_AZURE":      3,
		"PROVIDER_KUBERNETES": 4,
	}
)

func (x Provider) Enum() *Provider {
	p := new(Provider)
	*p = x
	return p
}

func (x Provider) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Provider) Descriptor() protoreflect.EnumDescriptor {
	return file_resource_v1_provider_proto_enumTypes[0].Descriptor()
}

func (Provider) Type() protoreflect.EnumType {
	return &file_resource_v1_provider_proto_enumTypes[0]
}

func (x Provider) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Provider.Descriptor instead.
func (Provider) EnumDescriptor() ([]byte, []int) {
	return file_resource_v1_provider_proto_rawDescGZIP(), []int{0}
}

// ProviderAccount contains provider account information
type ProviderAccount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	AccountName   string                 `protobuf:"bytes,2,opt,name=account_name,json=accountName,proto3" json:"account_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProviderAccount) Reset() {
	*x = ProviderAccount{}
	mi := &file_resource_v1_provider_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderAccount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderAccount) ProtoMessage() {}

func (x *ProviderAccount) ProtoReflect() protoreflect.Message {
	mi := &file_resource_v1_provider_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderAccount.ProtoReflect.Descriptor instead.
func (*ProviderAccount) Descriptor() ([]byte, []int) {
	return file_resource_v1_provider_proto_rawDescGZIP(), []int{0}
}

func (x *ProviderAccount) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *ProviderAccount) GetAccountName() string {
	if x != nil {
		return x.AccountName
	}
	return ""
}

var File_resource_v1_provider_proto protoreflect.FileDescriptor

const file_resource_v1_provider_proto_rawDesc = "" +
	"\n" +
	"\x1aresource/v1/provider.proto\x12\vresource.v1\"S\n" +
	"\x0fProviderAccount\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12!\n" +
	"\faccount_name\x18\x02 \x01(\tR\vaccountName*o\n" +
	"\bProvider\x12\x12\n" +
	"\x0ePROVIDER_OTHER\x10\x00\x12\x10\n" +
	"\fPROVIDER_AWS\x10\x01\x12\x10\n" +
	"\fPROVIDER_GCP\x10\x02\x12\x12\n" +
	"\x0ePROVIDER_AZURE\x10\x03\x12\x17\n" +
	"\x13PROVIDER_KUBERNETES\x10\x04B\xa8\x01\n" +
	"\x0fcom.resource.v1B\rProviderProtoP\x01Z9github.com/antimetal/agent/pkg/api/resource/v1;resourcev1\xa2\x02\x03RXX\xaa\x02\vResource.V1\xca\x02\vResource\\V1\xe2\x02\x17Resource\\V1\\GPBMetadata\xea\x02\fResource::V1b\x06proto3"

var (
	file_resource_v1_provider_proto_rawDescOnce sync.Once
	file_resource_v1_provider_proto_rawDescData []byte
)

func file_resource_v1_provider_proto_rawDescGZIP() []byte {
	file_resource_v1_provider_proto_rawDescOnce.Do(func() {
		file_resource_v1_provider_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_resource_v1_provider_proto_rawDesc), len(file_resource_v1_provider_proto_rawDesc)))
	})
	return file_resource_v1_provider_proto_rawDescData
}

var file_resource_v1_provider_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_resource_v1_provider_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_resource_v1_provider_proto_goTypes = []any{
	(Provider)(0),           // 0: resource.v1.Provider
	(*ProviderAccount)(nil), // 1: resource.v1.ProviderAccount
}
var file_resource_v1_provider_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_resource_v1_provider_proto_init() }
func file_resource_v1_provider_proto_init() {
	if File_resource_v1_provider_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_resource_v1_provider_proto_rawDesc), len(file_resource_v1_provider_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_resource_v1_provider_proto_goTypes,
		DependencyIndexes: file_resource_v1_provider_proto_depIdxs,
		EnumInfos:         file_resource_v1_provider_proto_enumTypes,
		MessageInfos:      file_resource_v1_provider_proto_msgTypes,
	}.Build()
	File_resource_v1_provider_proto = out.File
	file_resource_v1_provider_proto_goTypes = nil
	file_resource_v1_provider_proto_depIdxs = nil
}
