// Antimetal API definitions
// Copyright Antimetal, Inc. All rights reserved.
//
// Use of this source code and APIs are governed by a source available license that can be found in
// the LICENSE file or at:
// https://polyformproject.org/wp-content/uploads/2020/06/PolyForm-Shield-1.0.0.txt

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: resource/v1/relationship.proto

package resourcev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Relationship is a directed edge that represents a relationship between two Resources.
// It is defined like a triplet that contains a predicate, which defines what type of relationship
// it is, and a subject and object for the predicate. There can be multiple associations with the
// same predicate type attached to the same resource.
//
// Many relationships between Resources in the resource graph are bidirectional.
// Bidirectional edges are modeled as two separate Relationship objects. When Relationships are
// updated in the graph the inverse Relationships should be kept up to date.
type Relationship struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Describes the relationship type.
	Type *TypeDescriptor `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// Unique identifier for the relationship.
	Id []byte `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	// Resource id that is the subject of the predicate.
	Subject *ResourceRef `protobuf:"bytes,3,opt,name=subject,proto3" json:"subject,omitempty"`
	// Resource id that is the object of the predicate.
	Object *ResourceRef `protobuf:"bytes,4,opt,name=object,proto3" json:"object,omitempty"`
	// The predicate that defines the relationship.
	// The type is determined by the type field.
	Predicate *anypb.Any `protobuf:"bytes,5,opt,name=predicate,proto3" json:"predicate,omitempty"`
	// Creation time of the relationship.
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Time when the relationship was last updated.
	UpdatedAt *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// Deletion time of the relationship.
	DeletedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Relationship) Reset() {
	*x = Relationship{}
	mi := &file_resource_v1_relationship_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Relationship) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Relationship) ProtoMessage() {}

func (x *Relationship) ProtoReflect() protoreflect.Message {
	mi := &file_resource_v1_relationship_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Relationship.ProtoReflect.Descriptor instead.
func (*Relationship) Descriptor() ([]byte, []int) {
	return file_resource_v1_relationship_proto_rawDescGZIP(), []int{0}
}

func (x *Relationship) GetType() *TypeDescriptor {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *Relationship) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *Relationship) GetSubject() *ResourceRef {
	if x != nil {
		return x.Subject
	}
	return nil
}

func (x *Relationship) GetObject() *ResourceRef {
	if x != nil {
		return x.Object
	}
	return nil
}

func (x *Relationship) GetPredicate() *anypb.Any {
	if x != nil {
		return x.Predicate
	}
	return nil
}

func (x *Relationship) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Relationship) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Relationship) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

var File_resource_v1_relationship_proto protoreflect.FileDescriptor

const file_resource_v1_relationship_proto_rawDesc = "" +
	"\n" +
	"\x1eresource/v1/relationship.proto\x12\vresource.v1\x1a\x19google/protobuf/any.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x18resource/v1/object.proto\x1a\x1aresource/v1/resource.proto\"\x9a\x03\n" +
	"\fRelationship\x12/\n" +
	"\x04type\x18\x01 \x01(\v2\x1b.resource.v1.TypeDescriptorR\x04type\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\fR\x02id\x122\n" +
	"\asubject\x18\x03 \x01(\v2\x18.resource.v1.ResourceRefR\asubject\x120\n" +
	"\x06object\x18\x04 \x01(\v2\x18.resource.v1.ResourceRefR\x06object\x122\n" +
	"\tpredicate\x18\x05 \x01(\v2\x14.google.protobuf.AnyR\tpredicate\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x129\n" +
	"\n" +
	"deleted_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tdeletedAtB\xac\x01\n" +
	"\x0fcom.resource.v1B\x11RelationshipProtoP\x01Z9github.com/antimetal/agent/pkg/api/resource/v1;resourcev1\xa2\x02\x03RXX\xaa\x02\vResource.V1\xca\x02\vResource\\V1\xe2\x02\x17Resource\\V1\\GPBMetadata\xea\x02\fResource::V1b\x06proto3"

var (
	file_resource_v1_relationship_proto_rawDescOnce sync.Once
	file_resource_v1_relationship_proto_rawDescData []byte
)

func file_resource_v1_relationship_proto_rawDescGZIP() []byte {
	file_resource_v1_relationship_proto_rawDescOnce.Do(func() {
		file_resource_v1_relationship_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_resource_v1_relationship_proto_rawDesc), len(file_resource_v1_relationship_proto_rawDesc)))
	})
	return file_resource_v1_relationship_proto_rawDescData
}

var file_resource_v1_relationship_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_resource_v1_relationship_proto_goTypes = []any{
	(*Relationship)(nil),          // 0: resource.v1.Relationship
	(*TypeDescriptor)(nil),        // 1: resource.v1.TypeDescriptor
	(*ResourceRef)(nil),           // 2: resource.v1.ResourceRef
	(*anypb.Any)(nil),             // 3: google.protobuf.Any
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_resource_v1_relationship_proto_depIdxs = []int32{
	1, // 0: resource.v1.Relationship.type:type_name -> resource.v1.TypeDescriptor
	2, // 1: resource.v1.Relationship.subject:type_name -> resource.v1.ResourceRef
	2, // 2: resource.v1.Relationship.object:type_name -> resource.v1.ResourceRef
	3, // 3: resource.v1.Relationship.predicate:type_name -> google.protobuf.Any
	4, // 4: resource.v1.Relationship.created_at:type_name -> google.protobuf.Timestamp
	4, // 5: resource.v1.Relationship.updated_at:type_name -> google.protobuf.Timestamp
	4, // 6: resource.v1.Relationship.deleted_at:type_name -> google.protobuf.Timestamp
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_resource_v1_relationship_proto_init() }
func file_resource_v1_relationship_proto_init() {
	if File_resource_v1_relationship_proto != nil {
		return
	}
	file_resource_v1_object_proto_init()
	file_resource_v1_resource_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_resource_v1_relationship_proto_rawDesc), len(file_resource_v1_relationship_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_resource_v1_relationship_proto_goTypes,
		DependencyIndexes: file_resource_v1_relationship_proto_depIdxs,
		MessageInfos:      file_resource_v1_relationship_proto_msgTypes,
	}.Build()
	File_resource_v1_relationship_proto = out.File
	file_resource_v1_relationship_proto_goTypes = nil
	file_resource_v1_relationship_proto_depIdxs = nil
}
