// Antimetal API definitions
// Copyright Antimetal, Inc. All rights reserved.
//
// Use of this source code and APIs are governed by a source available license that can be found in
// the LICENSE file or at:
// https://polyformproject.org/wp-content/uploads/2020/06/PolyForm-Shield-1.0.0.txt

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: resource/v1/resource.proto

package resourcev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ResourceMeta is metadata that all resources have.
type ResourceMeta struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Resource ID
	Id []byte `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The provider that serves the resource.
	Provider Provider `protobuf:"varint,2,opt,name=provider,proto3,enum=resource.v1.Provider" json:"provider,omitempty"`
	// Provider resource ID
	ProviderId string `protobuf:"bytes,3,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"`
	// The provider account that owns the resource
	// Deprecated: use namespace instead.
	//
	// Deprecated: Marked as deprecated in resource/v1/resource.proto.
	Account *ProviderAccount `protobuf:"bytes,4,opt,name=account,proto3" json:"account,omitempty"`
	// Provider service the resource belongs to
	Service string `protobuf:"bytes,5,opt,name=service,proto3" json:"service,omitempty"`
	// Resource name
	Name string `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`
	// List of resource tags
	Tags []*Tag `protobuf:"bytes,7,rep,name=tags,proto3" json:"tags,omitempty"`
	// Provider resource group in which resource is contained.
	ProviderGroup string `protobuf:"bytes,8,opt,name=provider_group,json=providerGroup,proto3" json:"provider_group,omitempty"`
	// Region in which the resource is located.
	Region string `protobuf:"bytes,9,opt,name=region,proto3" json:"region,omitempty"`
	// Zone in which the resource is located.
	Zone string `protobuf:"bytes,10,opt,name=zone,proto3" json:"zone,omitempty"`
	// Creation time of the resource
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Time when the resource was last updated
	UpdatedAt *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// Deletion time of the resource
	DeletedAt *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	// The namespace scope of the resource.
	Namespace     *Namespace `protobuf:"bytes,14,opt,name=namespace,proto3" json:"namespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceMeta) Reset() {
	*x = ResourceMeta{}
	mi := &file_resource_v1_resource_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceMeta) ProtoMessage() {}

func (x *ResourceMeta) ProtoReflect() protoreflect.Message {
	mi := &file_resource_v1_resource_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceMeta.ProtoReflect.Descriptor instead.
func (*ResourceMeta) Descriptor() ([]byte, []int) {
	return file_resource_v1_resource_proto_rawDescGZIP(), []int{0}
}

func (x *ResourceMeta) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *ResourceMeta) GetProvider() Provider {
	if x != nil {
		return x.Provider
	}
	return Provider_PROVIDER_OTHER
}

func (x *ResourceMeta) GetProviderId() string {
	if x != nil {
		return x.ProviderId
	}
	return ""
}

// Deprecated: Marked as deprecated in resource/v1/resource.proto.
func (x *ResourceMeta) GetAccount() *ProviderAccount {
	if x != nil {
		return x.Account
	}
	return nil
}

func (x *ResourceMeta) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *ResourceMeta) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ResourceMeta) GetTags() []*Tag {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *ResourceMeta) GetProviderGroup() string {
	if x != nil {
		return x.ProviderGroup
	}
	return ""
}

func (x *ResourceMeta) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *ResourceMeta) GetZone() string {
	if x != nil {
		return x.Zone
	}
	return ""
}

func (x *ResourceMeta) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ResourceMeta) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *ResourceMeta) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

func (x *ResourceMeta) GetNamespace() *Namespace {
	if x != nil {
		return x.Namespace
	}
	return nil
}

// Tag is a key value pair that helps identify or describe a resource.
type Tag struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tag) Reset() {
	*x = Tag{}
	mi := &file_resource_v1_resource_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tag) ProtoMessage() {}

func (x *Tag) ProtoReflect() protoreflect.Message {
	mi := &file_resource_v1_resource_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tag.ProtoReflect.Descriptor instead.
func (*Tag) Descriptor() ([]byte, []int) {
	return file_resource_v1_resource_proto_rawDescGZIP(), []int{1}
}

func (x *Tag) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Tag) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// Resource is a typed node on the Infrastructure graph and represents an
// instance of a cloud resource.
type Resource struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Describes the resource type.
	Type *TypeDescriptor `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// Contains resource metadata.
	Metadata *ResourceMeta `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// The resource spec. The type of this field is determined by the type field.
	Spec          *anypb.Any `protobuf:"bytes,3,opt,name=spec,proto3" json:"spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resource) Reset() {
	*x = Resource{}
	mi := &file_resource_v1_resource_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resource) ProtoMessage() {}

func (x *Resource) ProtoReflect() protoreflect.Message {
	mi := &file_resource_v1_resource_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resource.ProtoReflect.Descriptor instead.
func (*Resource) Descriptor() ([]byte, []int) {
	return file_resource_v1_resource_proto_rawDescGZIP(), []int{2}
}

func (x *Resource) GetType() *TypeDescriptor {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *Resource) GetMetadata() *ResourceMeta {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Resource) GetSpec() *anypb.Any {
	if x != nil {
		return x.Spec
	}
	return nil
}

// ResourceRef unambiguously identifies a resource.
type ResourceRef struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Resource type URL.
	TypeUrl string `protobuf:"bytes,1,opt,name=type_url,json=typeUrl,proto3" json:"type_url,omitempty"`
	// Resource name
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// The namespace scope of the resource.
	Namespace     *Namespace `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceRef) Reset() {
	*x = ResourceRef{}
	mi := &file_resource_v1_resource_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceRef) ProtoMessage() {}

func (x *ResourceRef) ProtoReflect() protoreflect.Message {
	mi := &file_resource_v1_resource_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceRef.ProtoReflect.Descriptor instead.
func (*ResourceRef) Descriptor() ([]byte, []int) {
	return file_resource_v1_resource_proto_rawDescGZIP(), []int{3}
}

func (x *ResourceRef) GetTypeUrl() string {
	if x != nil {
		return x.TypeUrl
	}
	return ""
}

func (x *ResourceRef) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ResourceRef) GetNamespace() *Namespace {
	if x != nil {
		return x.Namespace
	}
	return nil
}

var File_resource_v1_resource_proto protoreflect.FileDescriptor

const file_resource_v1_resource_proto_rawDesc = "" +
	"\n" +
	"\x1aresource/v1/resource.proto\x12\vresource.v1\x1a\x19google/protobuf/any.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bresource/v1/namespace.proto\x1a\x18resource/v1/object.proto\x1a\x1aresource/v1/provider.proto\"\xbc\x04\n" +
	"\fResourceMeta\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02id\x121\n" +
	"\bprovider\x18\x02 \x01(\x0e2\x15.resource.v1.ProviderR\bprovider\x12\x1f\n" +
	"\vprovider_id\x18\x03 \x01(\tR\n" +
	"providerId\x12:\n" +
	"\aaccount\x18\x04 \x01(\v2\x1c.resource.v1.ProviderAccountB\x02\x18\x01R\aaccount\x12\x18\n" +
	"\aservice\x18\x05 \x01(\tR\aservice\x12\x12\n" +
	"\x04name\x18\x06 \x01(\tR\x04name\x12$\n" +
	"\x04tags\x18\a \x03(\v2\x10.resource.v1.TagR\x04tags\x12%\n" +
	"\x0eprovider_group\x18\b \x01(\tR\rproviderGroup\x12\x16\n" +
	"\x06region\x18\t \x01(\tR\x06region\x12\x12\n" +
	"\x04zone\x18\n" +
	" \x01(\tR\x04zone\x129\n" +
	"\n" +
	"created_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x129\n" +
	"\n" +
	"deleted_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tdeletedAt\x124\n" +
	"\tnamespace\x18\x0e \x01(\v2\x16.resource.v1.NamespaceR\tnamespace\"-\n" +
	"\x03Tag\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\x9c\x01\n" +
	"\bResource\x12/\n" +
	"\x04type\x18\x01 \x01(\v2\x1b.resource.v1.TypeDescriptorR\x04type\x125\n" +
	"\bmetadata\x18\x02 \x01(\v2\x19.resource.v1.ResourceMetaR\bmetadata\x12(\n" +
	"\x04spec\x18\x03 \x01(\v2\x14.google.protobuf.AnyR\x04spec\"r\n" +
	"\vResourceRef\x12\x19\n" +
	"\btype_url\x18\x01 \x01(\tR\atypeUrl\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x124\n" +
	"\tnamespace\x18\x03 \x01(\v2\x16.resource.v1.NamespaceR\tnamespaceB\xa8\x01\n" +
	"\x0fcom.resource.v1B\rResourceProtoP\x01Z9github.com/antimetal/agent/pkg/api/resource/v1;resourcev1\xa2\x02\x03RXX\xaa\x02\vResource.V1\xca\x02\vResource\\V1\xe2\x02\x17Resource\\V1\\GPBMetadata\xea\x02\fResource::V1b\x06proto3"

var (
	file_resource_v1_resource_proto_rawDescOnce sync.Once
	file_resource_v1_resource_proto_rawDescData []byte
)

func file_resource_v1_resource_proto_rawDescGZIP() []byte {
	file_resource_v1_resource_proto_rawDescOnce.Do(func() {
		file_resource_v1_resource_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_resource_v1_resource_proto_rawDesc), len(file_resource_v1_resource_proto_rawDesc)))
	})
	return file_resource_v1_resource_proto_rawDescData
}

var file_resource_v1_resource_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_resource_v1_resource_proto_goTypes = []any{
	(*ResourceMeta)(nil),          // 0: resource.v1.ResourceMeta
	(*Tag)(nil),                   // 1: resource.v1.Tag
	(*Resource)(nil),              // 2: resource.v1.Resource
	(*ResourceRef)(nil),           // 3: resource.v1.ResourceRef
	(Provider)(0),                 // 4: resource.v1.Provider
	(*ProviderAccount)(nil),       // 5: resource.v1.ProviderAccount
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
	(*Namespace)(nil),             // 7: resource.v1.Namespace
	(*TypeDescriptor)(nil),        // 8: resource.v1.TypeDescriptor
	(*anypb.Any)(nil),             // 9: google.protobuf.Any
}
var file_resource_v1_resource_proto_depIdxs = []int32{
	4,  // 0: resource.v1.ResourceMeta.provider:type_name -> resource.v1.Provider
	5,  // 1: resource.v1.ResourceMeta.account:type_name -> resource.v1.ProviderAccount
	1,  // 2: resource.v1.ResourceMeta.tags:type_name -> resource.v1.Tag
	6,  // 3: resource.v1.ResourceMeta.created_at:type_name -> google.protobuf.Timestamp
	6,  // 4: resource.v1.ResourceMeta.updated_at:type_name -> google.protobuf.Timestamp
	6,  // 5: resource.v1.ResourceMeta.deleted_at:type_name -> google.protobuf.Timestamp
	7,  // 6: resource.v1.ResourceMeta.namespace:type_name -> resource.v1.Namespace
	8,  // 7: resource.v1.Resource.type:type_name -> resource.v1.TypeDescriptor
	0,  // 8: resource.v1.Resource.metadata:type_name -> resource.v1.ResourceMeta
	9,  // 9: resource.v1.Resource.spec:type_name -> google.protobuf.Any
	7,  // 10: resource.v1.ResourceRef.namespace:type_name -> resource.v1.Namespace
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_resource_v1_resource_proto_init() }
func file_resource_v1_resource_proto_init() {
	if File_resource_v1_resource_proto != nil {
		return
	}
	file_resource_v1_namespace_proto_init()
	file_resource_v1_object_proto_init()
	file_resource_v1_provider_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_resource_v1_resource_proto_rawDesc), len(file_resource_v1_resource_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_resource_v1_resource_proto_goTypes,
		DependencyIndexes: file_resource_v1_resource_proto_depIdxs,
		MessageInfos:      file_resource_v1_resource_proto_msgTypes,
	}.Build()
	File_resource_v1_resource_proto = out.File
	file_resource_v1_resource_proto_goTypes = nil
	file_resource_v1_resource_proto_depIdxs = nil
}
