apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: antimetal
    app.kubernetes.io/name: antimetal-system
    app.kubernetes.io/component: namespace
    app.kubernetes.io/part-of: antimetal
  name: antimetal-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent
  labels:
    control-plane: antimetal
    app.kubernetes.io/name: antimetal-agent
    app.kubernetes.io/component: agent
    app.kubernetes.io/part-of: antimetal
spec:
  selector:
    matchLabels:
      control-plane: antimetal
  template:
    metadata:
      labels:
        control-plane: antimetal
        app.kubernetes.io/name: agent
        app.kubernetes.io/component: agent
        app.kubernetes.io/part-of: antimetal
    spec:
      # TODO(user): Uncomment the following code to configure the nodeAffinity expression
      # according to the platforms which are supported by your solution.
      # It is considered best practice to support multiple architectures. You can
      # build your manager image using the makefile target docker-buildx.
      # affinity:
      #   nodeAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #       nodeSelectorTerms:
      #         - matchExpressions:
      #           - key: kubernetes.io/arch
      #             operator: In
      #             values:
      #               - amd64
      #               - arm64
      #               - ppc64le
      #               - s390x
      #           - key: kubernetes.io/os
      #             operator: In
      #             values:
      #               - linux
      securityContext:
        runAsNonRoot: true
      containers:
      - name: agent
        command:
        - /agent
        args:
        - --leader-elect
        image: agent
        ports: []
        env:
        - name: KUBERNETES_NODE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: KUBERNETES_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: HOST_PROC
          value: /host/proc
        - name: HOST_SYS
          value: /host/sys
        - name: HOST_DEV
          value: /host/dev
        volumeMounts:
        - name: proc
          mountPath: /host/proc
          readOnly: true
        - name: sys
          mountPath: /host/sys
          readOnly: true
        - name: dev
          mountPath: /host/dev
          readOnly: true
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - "ALL"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 512Mi
      serviceAccountName: agent
      terminationGracePeriodSeconds: 10
      automountServiceAccountToken: true
      volumes:
      - name: proc
        hostPath:
          path: /proc
          type: Directory
      - name: sys
        hostPath:
          path: /sys
          type: Directory
      - name: dev
        hostPath:
          path: /dev
          type: Directory
