// Antimetal API definitions
// Copyright Antimetal, Inc. All rights reserved.
//
// Use of this source code and APIs are governed by a source available license that can be found in
// the LICENSE file or at:
// https://polyformproject.org/wp-content/uploads/2020/06/PolyForm-Shield-1.0.0.txt

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: kubernetes/v1/cluster.proto

package kubernetesv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ClusterProvider specifies the provider that is managing the Kubernetes Cluster.
type ClusterProvider int32

const (
	ClusterProvider_CLUSTER_PROVIDER_OTHER ClusterProvider = 0
	ClusterProvider_CLUSTER_PROVIDER_EKS   ClusterProvider = 1
	ClusterProvider_CLUSTER_PROVIDER_GKE   ClusterProvider = 2
	ClusterProvider_CLUSTER_PROVIDER_AKS   ClusterProvider = 3
	ClusterProvider_CLUSTER_PROVIDER_KIND  ClusterProvider = 4
)

// Enum value maps for ClusterProvider.
var (
	ClusterProvider_name = map[int32]string{
		0: "CLUSTER_PROVIDER_OTHER",
		1: "CLUSTER_PROVIDER_EKS",
		2: "CLUSTER_PROVIDER_GKE",
		3: "CLUSTER_PROVIDER_AKS",
		4: "CLUSTER_PROVIDER_KIND",
	}
	ClusterProvider_value = map[string]int32{
		"CLUSTER_PROVIDER_OTHER": 0,
		"CLUSTER_PROVIDER_EKS":   1,
		"CLUSTER_PROVIDER_GKE":   2,
		"CLUSTER_PROVIDER_AKS":   3,
		"CLUSTER_PROVIDER_KIND":  4,
	}
)

func (x ClusterProvider) Enum() *ClusterProvider {
	p := new(ClusterProvider)
	*p = x
	return p
}

func (x ClusterProvider) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ClusterProvider) Descriptor() protoreflect.EnumDescriptor {
	return file_kubernetes_v1_cluster_proto_enumTypes[0].Descriptor()
}

func (ClusterProvider) Type() protoreflect.EnumType {
	return &file_kubernetes_v1_cluster_proto_enumTypes[0]
}

func (x ClusterProvider) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ClusterProvider.Descriptor instead.
func (ClusterProvider) EnumDescriptor() ([]byte, []int) {
	return file_kubernetes_v1_cluster_proto_rawDescGZIP(), []int{0}
}

// Cluster contains information about a Kubernetes cluster.
type Cluster struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MajorVersion  string                 `protobuf:"bytes,1,opt,name=major_version,json=majorVersion,proto3" json:"major_version,omitempty"`
	MinorVersion  string                 `protobuf:"bytes,2,opt,name=minor_version,json=minorVersion,proto3" json:"minor_version,omitempty"`
	Provider      ClusterProvider        `protobuf:"varint,3,opt,name=provider,proto3,enum=kubernetes.v1.ClusterProvider" json:"provider,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cluster) Reset() {
	*x = Cluster{}
	mi := &file_kubernetes_v1_cluster_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cluster) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cluster) ProtoMessage() {}

func (x *Cluster) ProtoReflect() protoreflect.Message {
	mi := &file_kubernetes_v1_cluster_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cluster.ProtoReflect.Descriptor instead.
func (*Cluster) Descriptor() ([]byte, []int) {
	return file_kubernetes_v1_cluster_proto_rawDescGZIP(), []int{0}
}

func (x *Cluster) GetMajorVersion() string {
	if x != nil {
		return x.MajorVersion
	}
	return ""
}

func (x *Cluster) GetMinorVersion() string {
	if x != nil {
		return x.MinorVersion
	}
	return ""
}

func (x *Cluster) GetProvider() ClusterProvider {
	if x != nil {
		return x.Provider
	}
	return ClusterProvider_CLUSTER_PROVIDER_OTHER
}

var File_kubernetes_v1_cluster_proto protoreflect.FileDescriptor

const file_kubernetes_v1_cluster_proto_rawDesc = "" +
	"\n" +
	"\x1bkubernetes/v1/cluster.proto\x12\rkubernetes.v1\"\x8f\x01\n" +
	"\aCluster\x12#\n" +
	"\rmajor_version\x18\x01 \x01(\tR\fmajorVersion\x12#\n" +
	"\rminor_version\x18\x02 \x01(\tR\fminorVersion\x12:\n" +
	"\bprovider\x18\x03 \x01(\x0e2\x1e.kubernetes.v1.ClusterProviderR\bprovider*\x96\x01\n" +
	"\x0fClusterProvider\x12\x1a\n" +
	"\x16CLUSTER_PROVIDER_OTHER\x10\x00\x12\x18\n" +
	"\x14CLUSTER_PROVIDER_EKS\x10\x01\x12\x18\n" +
	"\x14CLUSTER_PROVIDER_GKE\x10\x02\x12\x18\n" +
	"\x14CLUSTER_PROVIDER_AKS\x10\x03\x12\x19\n" +
	"\x15CLUSTER_PROVIDER_KIND\x10\x04B\xb5\x01\n" +
	"\x11com.kubernetes.v1B\fClusterProtoP\x01Z=github.com/antimetal/agent/pkg/api/kubernetes/v1;kubernetesv1\xa2\x02\x03KXX\xaa\x02\rKubernetes.V1\xca\x02\rKubernetes\\V1\xe2\x02\x19Kubernetes\\V1\\GPBMetadata\xea\x02\x0eKubernetes::V1b\x06proto3"

var (
	file_kubernetes_v1_cluster_proto_rawDescOnce sync.Once
	file_kubernetes_v1_cluster_proto_rawDescData []byte
)

func file_kubernetes_v1_cluster_proto_rawDescGZIP() []byte {
	file_kubernetes_v1_cluster_proto_rawDescOnce.Do(func() {
		file_kubernetes_v1_cluster_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kubernetes_v1_cluster_proto_rawDesc), len(file_kubernetes_v1_cluster_proto_rawDesc)))
	})
	return file_kubernetes_v1_cluster_proto_rawDescData
}

var file_kubernetes_v1_cluster_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_kubernetes_v1_cluster_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_kubernetes_v1_cluster_proto_goTypes = []any{
	(ClusterProvider)(0), // 0: kubernetes.v1.ClusterProvider
	(*Cluster)(nil),      // 1: kubernetes.v1.Cluster
}
var file_kubernetes_v1_cluster_proto_depIdxs = []int32{
	0, // 0: kubernetes.v1.Cluster.provider:type_name -> kubernetes.v1.ClusterProvider
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_kubernetes_v1_cluster_proto_init() }
func file_kubernetes_v1_cluster_proto_init() {
	if File_kubernetes_v1_cluster_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kubernetes_v1_cluster_proto_rawDesc), len(file_kubernetes_v1_cluster_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kubernetes_v1_cluster_proto_goTypes,
		DependencyIndexes: file_kubernetes_v1_cluster_proto_depIdxs,
		EnumInfos:         file_kubernetes_v1_cluster_proto_enumTypes,
		MessageInfos:      file_kubernetes_v1_cluster_proto_msgTypes,
	}.Build()
	File_kubernetes_v1_cluster_proto = out.File
	file_kubernetes_v1_cluster_proto_goTypes = nil
	file_kubernetes_v1_cluster_proto_depIdxs = nil
}
